trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
- script: |     
    echo "Installing Google Chrome"     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb     sudo apt install -y ./google-chrome-stable_current_amd64.deb  
  displayName: 'Install Google Chrome'

- script: |
    cd '$(Build.SourcesDirectory)'
    npm install
  displayName: 'Install Dependencies'
 
- script: |
    cd '$(Build.SourcesDirectory)'
    npm run ui
  displayName: 'Run webdriverio feature'
  continueOnError: true
 
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/.tmp/report/'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'reports'
    publishLocation: 'Container'